[build]
command = "npm run compile"
publish = "_site"

[functions]
directory = "functions"

[[redirects]]
from = "/next"
to = "/.netlify/functions/next"
status = 303

[[redirects]]
from = "/prev"
to = "/.netlify/functions/prev"
status = 303

[[redirects]]
from = "/random"
to = "/.netlify/functions/random"
status = 303
