[build]
  command = "npm run compile"
  publish = "_site"

[functions]
  directory = "functions"


[[redirects]]
    from = "/next"
    to = "/.netlify/functions/next"
    status = 301
    force = true

[[redirects]]
    from = "/prev"
    to = "/.netlify/functions/prev"
    status = 301
    force = true

[[redirects]]
    from = "/random"
    to = "/.netlify/functions/random"
    status = 301
    force = true
