[build]
  command = "npm run build"
  publish = "_site"
  Functions = "functions"

[[redirects]]
    from = "/next"
    to = "/.netlify/functions/next"
    status = 301
    force = true

[[redirects]]
    from = "/prev"
    to = "/.netlify/functions/prev"
    status = 301
    force = true

[[redirects]]
    from = "/random"
    to = "/.netlify/functions/random"
    status = 301
    force = true
